### ISSUE TITLE
BUG: clicking "Save this book" fails with error 400, "Unknown argument \"authors\" on field \"Mutation.saveBook\"."

### ISSUE THREAD

**Issue by iseanc** [iseanc/mern-book-search#19]
**ERROR: {"errors":[{"message":"Unknown argument \"authors\" on field \"Mutation.saveBook\".","extensions":**
{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Unknown argument \"authors\" on field \"Mutation.saveBook\".","    at Object.Argument (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/KnownArgumentNamesRule.js:46:11)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Unknown argument \"bookId\" on field \"Mutation.saveBook\". Did you mean \"book\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Unknown argument \"bookId\" on field \"Mutation.saveBook\". Did you mean \"book\"?","    at Object.Argument (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/KnownArgumentNamesRule.js:46:11)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Unknown argument \"description\" on field \"Mutation.saveBook\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Unknown argument \"description\" on field \"Mutation.saveBook\".","    at Object.Argument (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/KnownArgumentNamesRule.js:46:11)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Unknown argument \"image\" on field \"Mutation.saveBook\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Unknown argument \"image\" on field \"Mutation.saveBook\".","    at Object.Argument (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/KnownArgumentNamesRule.js:46:11)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Unknown argument \"title\" on field \"Mutation.saveBook\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Unknown argument \"title\" on field \"Mutation.saveBook\".","    at Object.Argument (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/KnownArgumentNamesRule.js:46:11)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Unknown argument \"link\" on field \"Mutation.saveBook\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Unknown argument \"link\" on field \"Mutation.saveBook\".","    at Object.Argument (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/KnownArgumentNamesRule.js:46:11)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Cannot query field \"authors\" on type \"User\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"authors\" on type \"User\".","    at Object.Field (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Cannot query field \"bookId\" on type \"User\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"bookId\" on type \"User\".","    at Object.Field (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Cannot query field \"description\" on type \"User\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"description\" on type \"User\".","    at Object.Field (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Cannot query field \"title\" on type \"User\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"title\" on type \"User\".","    at Object.Field (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Cannot query field \"image\" on type \"User\". Did you mean \"email\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"image\" on type \"User\". Did you mean \"email\"?","    at Object.Field (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Cannot query field \"link\" on type \"User\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"link\" on type \"User\".","    at Object.Field (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}},{"message":"Field \"saveBook\" argument \"book\" of type \"BookArgs!\" is required, but it was not provided.","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Field \"saveBook\" argument \"book\" of type \"BookArgs!\" is required, but it was not provided.","    at Object.leave (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/rules/ProvidedRequiredArgumentsRule.js:60:15)","    at Object.leave (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:324:32)","    at Object.leave (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/utilities/TypeInfo.js:411:21)","    at visit (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/language/visitor.js:197:21)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/graphql/validation/validate.js:91:24)","    at validate (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/Users/seancollins/Library/CloudStorage/OneDrive-Personal/bootcamp/challenges/mern-book-search/server/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}}]}

**Comment by iseanc** [comment]
FIXED.
